### ISSUE TITLE
NewDestination() appears to return a key pair with newline, intended behavior?

### ISSUE THREAD

**Issue by hkh4n** [eyedeekay/i2pkeys#4] opened 2024-09-15 19:21 UTC
While writing tests for keys, I found this anomaly. Pretty much self explanatory once you run the subtest "LoadKeysIncompat" here https://github.com/eyedeekay/i2pkeys/commit/ada0d39af44962e310d4a4661f4ad8d1b16c5f52:

	t.Run("LoadKeysIncompat", func(t *testing.T) {
		//extract keys
		addr := keys.Address
		fmt.Println(addr)

		//both := removeNewlines(keys.Both)
		both := keys.Both
		fmt.Println(both)

		//FORMAT TO LOAD: (Address, Both)
		addrload := addr.Base64() + "\n" + both

		r := strings.NewReader(addrload)
		loadedKeys, err := LoadKeysIncompat(r)
		if err != nil {
			t.Fatalf("LoadKeysIncompat failed: %v", err)
		}

		if loadedKeys.Address != keys.Address {
			//fmt.Printf("loadedKeys.Address md5hash: '%s'\n keys.Address md5hash: '%s'\n", getMD5Hash(string(loadedKeys.Address)), getMD5Hash(string(keys.Address)))
			t.Errorf("LoadKeysIncompat returned incorrect address. Got '%s', want '%s'", loadedKeys.Address, keys.Address)

		}
		if loadedKeys.Both != keys.Both {
			t.Errorf("LoadKeysIncompat returned incorrect pair. Got '%s'\nwant '%s'\n", loadedKeys.Both, keys.Both)
			if loadedKeys.Both == removeNewlines(keys.Both) {
				fmt.Println("However, both pairs are correct if newline is removed in generated keys.")
			}
		}

	})

Output:
```
However, both pairs are correct if newline is removed in generated keys.
    --- FAIL: Test_KeyGenerationAndHandling/LoadKeysIncompat (0.00s)
```

So the keys are correct, but is this intended behavior?

**Comment by eyedeekay** [comment] 2024-09-15 23:20
It was probably intended behavior at some point years ago when I knew a lot less, but I think changing the behavior might be the right thing to do. Is probably the right thing to do. Take out the newline, see what breaks if anything.

**Comment by hkh4n** [comment] 2024-09-16 01:57
> It was probably intended behavior at some point years ago when I knew a lot less, but I think changing the behavior might be the right thing to do. Is probably the right thing to do. Take out the newline, see what breaks if anything.

Got it, and done. It appeared to not break anything at least with the tests. They all run with success :D. Here is the PR: https://github.com/eyedeekay/i2pkeys/pull/3

**Comment by eyedeekay** [comment] 2024-09-17 23:36
OK closing here after the merge. Thanks once again for the contribution :)

**Closed as completed by eyedeekay** 2024-09-17 23:36 UTC
